src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Security\Http\Authentication\UserAuthenticatorInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
class User implements PasswordAuthenticatedUserInterface,UserInterface
{


    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"First Name is required")]
    #[Assert\Length(
        min: 3,
        max: 10,
    )]
    #[Assert\Regex(
        pattern: '/^[a-z]+$/i',
        message: 'the first name must only contains characters[a-z].'
    )]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    #[Assert\Length(
        min: 3,
        max: 10,
        exactMessage: 'less characters for your last name'
    )]
    #[Assert\Regex(
        pattern: '/^[a-z]+$/i',
        message: 'the last name must only contains characters[a-z].'
    )]
    #[Assert\NotBlank(message:"Last Name is required")]
    private ?string $prenom = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"Mail please")]
    #[Assert\Email(
        message: 'The email {{ value }} is not a valid email.',
    )]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"Password is required")]
    #[Assert\Regex(
        pattern: '/^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%^&*()-_=+{};:,<.>]).{8,}$/',
        message: 'Your password is too weak. Please include at least one uppercase letter, one lowercase letter, one digit, and one special character.'
    )]
    private ?string $pwd = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Assert\NotBlank(message:"Birthday date is required")]
    #[Assert\LessThan("today")]
    private ?\DateTimeInterface $date_N = null;

    #[ORM\Column(length: 255)]
    private ?string $role = null;

    #[ORM\Column(length: 255)]
    #[Assert\Length(
        min: 15,
        max: 150,
        exactMessage: 'less characters for your last name'
    )]
    #[Assert\NotBlank(message:"Adress is required")]
    private ?string $adress = null;


    #[ORM\Column(length: 255)]
    private ?string $photo = null;

    #[ORM\Column(length: 255)]
    private ?string $status = "inactive";

    #[ORM\Column(length: 255)]
    private ?string $num_tel = null;


    #[ORM\OneToMany(mappedBy: 'Author', targetEntity: Post::class)]
    private Collection $posts;

    #[ORM\OneToOne(mappedBy: 'user',targetEntity: 'Panier', cascade: ['persist', 'remove'])]
    private ?Panier $panier = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Commande::class)]
    private Collection $commandes;


    #[ORM\OneToMany(targetEntity: Session::class, mappedBy: 'coach')]
    private Collection $sessions;

    #[ORM\OneToMany(targetEntity: Reservation::class, mappedBy: 'User')]
    private Collection $reservations;
    public function __construct()
    {
        $this->sessions = new ArrayCollection();
        $this->reservations = new ArrayCollection();
        $this->commentaire = new ArrayCollection();
        $this->posts = new ArrayCollection();
        $this->panier = new Panier($this);
        $this->commandes = new ArrayCollection();
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getCommentaire(): Collection
    {
        return $this->commentaire;
    }

    public function addCommentaire(Comment $commentaire): static
    {
        if (!$this->commentaire->contains($commentaire)) {
            $this->commentaire->add($commentaire);
            $commentaire->setIdUser($this);
        }

        return $this;
    }

    public function removeCommentaire(Comment $commentaire): static
    {
        if ($this->commentaire->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getIdUser() === $this) {
                $commentaire->setIdUser(null);
            }
        }

        return $this;
    }



    /**
     * @return Collection<int, Post>
     */
    public function getPosts(): Collection
    {
        return $this->posts;
    }

    public function addPost(Post $post): static
    {
        if (!$this->posts->contains($post)) {
            $this->posts->add($post);
            $post->setAuthor($this);
        }

        return $this;
    }

    public function removePost(Post $post): static
    {
        if ($this->posts->removeElement($post)) {
            // set the owning side to null (unless already changed)
            if ($post->getAuthor() === $this) {
                $post->setAuthor(null);
            }
        }

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getPwd(): ?string
    {
        return $this->pwd;
    }

    public function setPwd(string $pwd): static
    {
        $this->pwd = $pwd;

        return $this;
    }

    public function getDateN(): ?\DateTimeInterface
    {
        return $this->date_N;
    }

    public function setDateN(\DateTimeInterface $date_N): static
    {
        $this->date_N = $date_N;

        return $this;
    }

    public function getRole(): ?string
    {
        return $this->role;
    }

    public function setRole(string $role): static
    {
        $this->role = $role;

        return $this;
    }
    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): static
    {
        $this->photo = $photo;

        return $this;
    }
    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): static
    {
        $this->adress = $adress;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->pwd;
        // TODO: Implement getPassword() method.
    }

    public function getRoles()
    {
        // Return an array of roles for the user, e.g., ['ROLE_USER']
        return ['ROLE_USER'];
    }

    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }

    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    public function getUsername()
    {
        // TODO: Implement getUsername() method.
        return $this->getEmail();
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getNum_tel(): ?string
    {
        return $this->num_tel;
    }

    public function setNum_tel(string $num_tel): static
    {
        $this->num_tel = $num_tel;

        return $this;
    }
    public function getNumTel(): ?string
    {
        return $this->num_tel;
    }

    public function setNumTel(string $num_tel): static
    {
        $this->num_tel = $num_tel;

        return $this;
    }
    public function __toString()
    {
        return $this->id ." ". $this->nom;
    }

    public function getPanier(): ?Panier
    {
        return $this->panier;
    }

    public function setPanier(?Panier $panier): static
    {
        // unset the owning side of the relation if necessary
        if ($panier === null && $this->panier !== null) {
            $this->panier->setUser(null);
        }

        // set the owning side of the relation if necessary
        if ($panier !== null && $panier->getUser() !== $this) {
            $panier->setUser($this);
        }

        $this->panier = $panier;

        return $this;
    }


    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): static
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes->add($commande);
            $commande->setUser($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): static
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getUser() === $this) {
                $commande->setUser(null);
            }
        }

        return $this;
    }

    public function addReservation(Reservation $reservation): static
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations->add($reservation);
            $reservation->setUser($this);
        }

        return $this;
    }
    public function addSession(Session $session): static
    {
        if (!$this->sessions->contains($session)) {
            $this->sessions->add($session);
            $session->setCoach($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Session>
     */
    public function getSessions(): Collection
    {

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Karser\Recaptcha3Bundle\Form\Recaptcha3Type;
use Karser\Recaptcha3Bundle\Validator\Constraints\Recaptcha3;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\DataTransformerInterface;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Validator\Constraints\IsTrue;
use VictorPrdh\RecaptchaBundle\Form\ReCaptchaType;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('prenom')
            ->add('email')
            ->add('pwd',PasswordType::class)
            ->add('date_N')
            ->add('num_tel')
            ->add('adress')
            ->add('photo', FileType::class, [
                'label' => 'Image',
                'required' => false, // Si l'image n'est pas obligatoire
                'mapped' => false, // Ne pas mapper directement le champ à l'entité
            ])
            ->add('role', ChoiceType::class, [
                'label' => 'role',
                'choices' => [
                    'Client' => 'client',
                    'Coach' => 'coach',
                ],
                'expanded' => true, // Set to true for radio buttons, false for a dropdown
                'multiple' => false, // Set to true for multiple choices
            ])
            ->add('captcha', Recaptcha3Type::class, [
                'constraints' => new Recaptcha3 ([
                    'message' => 'karser_recaptcha3.message',
                    'messageMissingValue' => 'karser_recaptcha3.message_missing_value',
                ]),
            ]);
        $builder->get('photo')->addModelTransformer(new FileToViewTransformerr());

    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

class FileToViewTransformerr implements DataTransformerInterface
{
    public function transform($value)
    {
        // Lors de l'affichage du formulaire, retournez null pour éviter les erreurs
        return null;
    }

    public function reverseTransform($value)
    {
        // Transformez le chemin de fichier en instance de Symfony\Component\HttpFoundation\File\File
        // Si $value est null, retournez null
        if (!$value) {
            return null;
        }

        return new File($value);
    }
}

templates/user/HomeOnCoach.html.twig
{% extends 'basefront.html.twig' %}
{% block menu %}
    <nav class="navbar navbar-expand-lg navigation fixed-top" id="navbar">
        <div class="container-fluid">
            <a class="navbar-brand" href="">
                <h2 class="text-white text-capitalize"></i>Breathe<span class="text-color">Out</span></h2>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsid"
                    aria-controls="navbarsid" aria-expanded="false" aria-label="Toggle navigation">
                <span class="ti-view-list"></span>
            </button>
            <div class="collapse text-center navbar-collapse" id="navbarsid">
                <ul class="navbar-nav mx-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="index.html">Boutique<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true"
                           aria-expanded="false">Entrainement</a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="">Exercices</a></li>
                            <li><a class="dropdown-item" href="">Défis</a></li>

                        </ul>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="service.html">Sessions</a></li>
                    <li class="nav-item"><a class="nav-link" href="pricing.html">Coachs</a></li>
                    <li class="nav-item"><a class="nav-link" href="pricing.html">Blog</a></li>
                    <li class="nav-item"><a class="nav-link" href="contact.html">A propos de nous</a></li>
                </ul>
                <li class="nav-item dropdown">
                    <a href="{{ path('app_user_show', {'id': app.user.getId()}) }}" class="nav-link dropdown-toggle">
                        <h3 class="text-color mb-0" style="margin-right: 10px;">
                            <i></i>{{ user.prenom }} {{ user.nom }}
                        </h3>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{{ path('app_user_show', {'id': app.user.getId()}) }}">Profile</a></li>
                        <li><a class="dropdown-item" href="{{ path('app_logout') }}">Log Out</a></li>
                    </ul>
                </li>
                <div class="my-md-0 ml-lg-4 mt-4 mt-lg-0 ml-auto text-lg-right mb-3 mb-lg-0">

                </div>
            </div>
        </div>
    </nav>
{% endblock %}
{% block title %}home COACH{% endblock %}

{% block up%}
    <section class="slider">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <br>
                    <span class="h6 d-inline-block mb-4 subhead text-uppercase">Home Page</span>
                    <h1 class="text-uppercase text-white mb-5">Hello Coach<span class="text-color"><br>{{ app.user.getPrenom() }} </span><br>To your Home Page</h1>

                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('app_user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

templates/user/delete_back.html.twig
<form method="post" action="{{ path('app_user_back_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

templates/user/edit.html.twig
{% extends '/user/HomeOnclient.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block up%}
    <section class="slider">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <br>
                    <span class="h6 d-inline-block mb-4 subhead text-uppercase">Home Page</span>
                    <h1 class="text-uppercase text-white mb-5">Hello<span class="text-color"><br>{{ app.user.getPrenom() }} </span><br>To your Home Page</h1>

                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block body %}
    <div class="container mt-5">
        <h1>Edit User</h1>

        <form method="post" action="{{ path('app_user_edit', {'id': user.id}) }}" enctype="multipart/form-data">
            {{ form_start(form) }}

            <div class="form-group">
                {{ form_label(form.nom, 'Nom', {'label_attr': {'class': 'font-weight-bold'}}) }}
                {{ form_widget(form.nom, {'attr': {'class': 'form-control'}}) }}
            </div>

            <div class="form-group">
                {{ form_label(form.prenom, 'Prenom', {'label_attr': {'class': 'font-weight-bold'}}) }}
                {{ form_widget(form.prenom, {'attr': {'class': 'form-control'}}) }}
            </div>

            <div class="form-group">
                {{ form_label(form.email, 'Email', {'label_attr': {'class': 'font-weight-bold'}}) }}
                {{ form_widget(form.email, {'attr': {'class': 'form-control'}}) }}
            </div>

            <div class="form-group">
                {{ form_label(form.adress, 'Adress', {'label_attr': {'class': 'font-weight-bold'}}) }}
                {{ form_widget(form.adress, {'attr': {'class': 'form-control'}}) }}
            </div>

            <div class="form-group">
                {{ form_label(form.photo, 'Image', {'label_attr': {'class': 'font-weight-bold'}}) }}
                {{ form_widget(form.photo, {'attr': {'class': 'form-control-file'}}) }}
            </div>

            <div class="form-group">
                {{ form_label(form.num_tel, 'Phone number', {'label_attr': {'class': 'font-weight-bold'}}) }}
                {{ form_widget(form.num_tel, {'attr': {'class': 'form-control'}}) }}
            </div>

            <button type="submit" class="btn btn-primary mt-3">Save Changes</button>

            {{ form_end(form) }}
        </form>

        <a href="{{ path('app_user_show', {'id': app.user.getId()}) }}" class="btn btn-secondary mt-3">Cancel</a>

        {{ include('user/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/user/edit_back.html.twig
{% extends '/userHomeOnAd.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block body %}
    <h1>Edit User</h1>
    {{ include('user/form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_user_back_show', {'id': user.id}) }}">view profile</a>
    {{ include('user/delete_back.html.twig') }}

{% endblock %}

templates/user/form.html.twig
{{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
    {{ form_widget(form) }}
<button class="btn">{{ button_label|default('update') }}</button>
{{ form_end(form) }}

templates/user/new.html.twig
{% extends 'basefront.html.twig' %}



{% block up%}


    <section class="slider">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <span class="h6 d-inline-block mb-4 subhead text-uppercase">Create account</span>
                    <h1 class="text-uppercase text-white mb-5">Welcome On Our <span class="text-color">fitness </span><br>Website</h1>

                 </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block body %}

    <body id="body">
<div class="hero-slider">
    <div class="slider-item th-fullpage hero-area d-flex align-items-center justify-content-center" style="background-image: url({{ asset('front/images/slider/envi.jpg')}});" style="height: 100vh;">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="card-body">
                        <h1 class="text-black-50">  Sign Up </h1>
                        <div class="form-container">
                            {{ form_start(form,{'attr':{'novalidate':'novalidate', 'class': 'text-white','class': 'text-danger'}}) }}
                            {{ form_label(form.nom,"Nom", {'label_attr': {'class': 'text-black'}}) }}
                            {{ form_errors(form.nom, {'attr': {'class': 'text-danger'}}) }}
                            {{ form_widget(form.nom, {'attr': {'class': 'form-control'}}) }}

                            {{ form_label(form.prenom,"Prenom", {'label_attr': {'class': 'text-black'}}) }}
                            {{ form_errors(form.prenom, {'attr': {'class': 'text-danger'}}) }}
                            {{ form_widget(form.prenom, {'attr': {'class': 'form-control'}}) }}

                            {{ form_label(form.email,"Email", {'label_attr': {'class': 'text-black'}}) }}
                            {{ form_errors(form.email, {'attr': {'class': 'text-danger'}}) }}
                            {{ form_widget(form.email, {'attr': {'class': 'form-control'}}) }}

                            {{ form_label(form.pwd,"Mot de passe", {'label_attr': {'class': 'text-black'}}) }}
                            {{ form_errors(form.pwd, {'attr': {'class': 'text-danger'}}) }}
                            {{ form_widget(form.pwd, {'attr': {'class': 'form-control'}}) }}

                            {{ form_label(form.date_N,"Date de naissance", {'label_attr': {'class': 'text-black'}}) }}
                            {{ form_errors(form.date_N, {'attr': {'class': 'text-danger'}}) }}
                            {{ form_widget(form.date_N, {'attr': {'class': 'form-control'}}) }}

                            {{ form_label(form.num_tel,"Numero de telephone", {'label_attr': {'class': 'text-black'}}) }}
                            {{ form_errors(form.num_tel, {'attr': {'class': 'text-danger'}}) }}
                            {{ form_widget(form.num_tel, {'attr': {'class': 'form-control'}}) }}

                            {{ form_label(form.adress,"Votre Addresse", {'label_attr': {'class': 'text-black'}}) }}
                            {{ form_errors(form.adress, {'attr': {'class': 'text-danger'}}) }}
                            {{ form_widget(form.adress, {'attr': {'class': 'form-control'}}) }}

                            {{ form_label(form.photo,"Photo", {'label_attr': {'class': 'text-black'}}) }}
                            {{ form_errors(form.photo, {'attr': {'class': 'text-danger'}}) }}
                            {{ form_widget(form.photo, {'attr': {'class': 'form-control'}}) }}

                            {{ form_label(form.role,"Role", {'label_attr': {'class': 'text-black'}}) }}
                            {{ form_errors(form.role, {'attr': {'class': 'text-danger'}}) }}
                            {{ form_widget(form.role, {'attr': {'class': 'form-control'}}) }}



                            <button class="btn">{{ button_label|default('Sign up') }}<a href="{{ path('app_login') }}"></a> </button>
                            {{ form_end(form) }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>





{% endblock %}

templates/user/new_back.html.twig
{% extends 'baseback.html.twig' %}



{% block body %}
    <h1>Create new User</h1>

    {{ include('user/_form.html.twig') }}

    <a href="{{ path('app_user_index') }}">back to list</a>
{% endblock %}

templates/user/show.html.twig
{% extends '/user/HomeOnclient.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
    <div class="container mt-5">
        <h1>User Details</h1>

        <table class="table table-bordered mt-4">
            <tbody>
            <tr>
                <th>ID</th>
                <td>{{ user.id }}</td>
            </tr>

            <tr>
                <th>Nom</th>
                <td>{{ user.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ user.prenom }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ user.adress }}</td>
            </tr>
            <tr>
                <th>PHOTO</th>
                <td>
                    {% if user.photo %}
                        <img src="{{ asset('/' ~ user.photo) }}" alt="User Photo" class="img-fluid">
                    {% else %}
                        No photo available
                    {% endif %}
                </td>
            </tr>

            <tr>
                <th>Date of Birth</th>
                <td>{{ user.dateN ? user.dateN|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Role</th>
                <td>{{ user.role }}</td>
            </tr>
            </tbody>
        </table>

        <a href="{{ path('app_user_edit', {'id': app.user.getId()}) }}" class="btn btn-primary mt-3">Edit</a>
        <a href="{{ path('app_logout') }}" class="btn btn-danger mt-3">Logout</a>

        {{ include('user/_delete_form.html.twig') }}
    </div>
{% endblock %}


{% block up%}
    <section class="slider">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <br>
                    <span class="h6 d-inline-block mb-4 subhead text-uppercase">Home Page</span>
                    <h1 class="text-uppercase text-white mb-5">Hello<span class="text-color"><br>{{ app.user.getPrenom() }} </span><br>To your Home Page</h1>

                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/user/show_back.html.twig
{% extends 'baseback.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
    <div class="container mt-5">
        <h1>User Details</h1>

        <table class="table mt-4">
            <tbody>
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ user.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ user.prenom }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>Pwd</th>
                <td>{{ user.pwd }}</td>
            </tr>
            <tr>
                <th>Date_N</th>
                <td>{{ user.dateN ? user.dateN|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Role</th>
                <td>{{ user.role }}</td>
            </tr>
            </tbody>
        </table>

        <a href="{{ path('app_user_index', {'id': app.user.getId()}) }}" class="btn btn-primary">Back to List</a>

        {{ include('user/delete_back.html.twig') }}
    </div>
{% endblock %}

templates/user/user_forgot_password.html.twig
{% extends 'basefront.html.twig' %}



{% block up%}


    <section class="slider">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <span class="h6 d-inline-block mb-4 subhead text-uppercase">Create account</span>
                    <h1 class="text-uppercase text-white mb-5">Welcome On Our <span class="text-color">fitness </span><br>Website</h1>

                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block body %}
    {% for message in app.flashes('error') %}

        <div class="alert alert-danger">
            {{ message }}
        </div>

    {% endfor %}
    <body id="body">
    <div class="hero-slider">
        <div class="slider-item th-fullpage hero-area d-flex align-items-center justify-content-center" style="background-image: url({{ asset('front/images/slider/envi.jpg')}});" style="height: 100vh;">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <div class="card-body">
                            <h1 class="text-black-50"> WRITE YOUR NUMBER </h1>
                            <div class="form-container">
                                {{ form_start(form,{'attr':{'novalidate':'novalidate', 'class': 'text-white','class': 'text-danger'}}) }}

                                {{ form_widget(form) }}
                                {{ form_end(form) }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}